export const lifeOsProject = {
  id: 'life-os',
  title: 'Life OS',
  category: 'MERN Stack',
  overview:
    'A production-ready, single-user personal operating system that unifies daily planning, journaling, finances, habits, health, study, spiritual practice, and data export in one dashboard.',
  technologies: [
    { name: 'React' },
    { name: 'Vite' },
    { name: 'Node.js' },
    { name: 'Express' },
    { name: 'MongoDB' },
    { name: 'Mongoose' },
    { name: 'Tailwind CSS' },
    { name: 'JWT' },
    { name: 'Firebase' },
    { name: 'Vercel' },
  ],
  architecture: [
    'React and Vite power a responsive client application with route-based modules, reusable UI components, light and dark theme support, React Query data fetching, and Recharts visualizations.',
    'A Node.js and Express API provides authenticated CRUD endpoints, dashboard aggregation, reports, and complete JSON data export.',
    'MongoDB with Mongoose persists user-scoped personal-management data, with compound user-and-date indexes for date-driven modules.',
    'JWT authentication, bcrypt password hashing, Helmet headers, rate limiting, CORS restrictions, and environment-based secrets protect the application.',
  ],
  challenges: [
    'Combining ten distinct personal-management modules into a cohesive dashboard without turning daily logging into a high-friction workflow.',
    'Building dependable computed features such as habit streaks, Salah progress, nutrition and exercise calculations, and cross-module dashboard summaries.',
    'Keeping sensitive personal, financial, and health data secure while providing reliable export and backup-oriented workflows.',
  ],
  lessonsLearned: [
    'A unified dashboard is most useful when each module can gracefully handle empty, loading, and error states independently.',
    'Business-critical calculations such as streaks, calorie totals, and date-based financial reports need server-side validation and dedicated automated tests.',
    'Production readiness for personal data tools requires security controls, indexes, exports, backups, monitoring, and mobile usability alongside feature development.',
  ],
  futureImprovements: [
    'Add native mobile applications and offline-first synchronization.',
    'Introduce third-party calendar integrations and optional AI-powered suggestions.',
    'Expand beyond the current single-user experience with carefully designed multi-user or social capabilities.',
  ],
  githubUrl: 'https://github.com/MSabbirHossen/Life-OS',
  liveUrl: 'https://life-os-lime-pi.vercel.app',
  screenshots: [],
  featured: true,
  status: 'Completed',
  year: '2026',
  role: 'Solo Developer',
  duration: 'Ongoing',
  teamSize: '1',
  client: 'Personal',
  difficulty: 'Advanced',
  featuredOrder: 1,
};
